### ISSUE TITLE
App not loading - 'YouTube Music is taking longer than usual to load'

### ISSUE THREAD

**Issue by jedihercules** [adlerluiz/ytmdesktop#1627]
### Consent

- [x] I verified that there is no open/closed issue for the same subject.
- [x] I understand that **YTMDesktop have NO affiliation with Google or YouTube**

### Current Behavior

I have been using YTMD for years and love it! I occasionally run into this issue of YouTube Music is taking longer than usual to load. 

<img width="926" height="617" alt="Image" src="https://github.com/user-attachments/assets/6c8ad24d-de09-4d0a-a78f-8f4b63abbe26" />

I tried reinstalling the latest version (confirmed I was already running it as well) but still popping the same message. 

### Expected Behavior

App would normally load into last played list/tracks

### Steps To Reproduce

Launch app
App says YouTube Music loaded
"YouTube Music is taking longer than usual to load" - Receive this message

### YTMDesktop

2.0.10

### OS

Windows

### OS Version

11

### Arch

x64

### Installation way

.exe

### Anything else?

Again, absolutely love the app! Thank you 🥇 💯

**Comment by Alipoodle** [comment]
Could you share your Log file in GitHub or Discord?

**Comment by jedihercules** [comment]
> Could you share your Log file in GitHub or Discord?

How/Where would I do that? :)

**Comment by Alipoodle** [comment]
> > Could you share your Log file in GitHub or Discord?
> 
> How/Where would I do that? :)

The file is at `%appdata%/YouTube Music Desktop App/logs`

Either drop the file in here?
Or Join the Discord (via the button on the Read Me)

**Comment by jedihercules** [comment]
Here is the log file 👍

[main.log](https://github.com/user-attachments/files/23937144/main.log)

**Comment by Alipoodle** [comment]
That's interesting not even an error firing. 🤔 
Appears like the event isn't firing to deem that YTM has loaded.

To my knowledge this should be fixed in up coming versions of the app~

**Comment by tibitTW** [comment]
I met the same issue on MacOS 26.1 and youtube music 2.0.0 :<

OS: macOS Tahoe 26.1 (25B78) arm64

```
$ brew info ytmdesktop-youtube-music
==> ytmdesktop-youtube-music: 2.0.0
https://ytmdesktop.app/
Deprecated because it does not pass the macOS Gatekeeper check! It will be disabled on 2026-09-01.
Installed
/opt/homebrew/Caskroom/ytmdesktop-youtube-music/2.0.0 (238.9MB)
  Installed using the formulae.brew.sh API on 2025-12-19 at 09:32:22
From: https://github.com/Homebrew/homebrew-cask/blob/HEAD/Casks/y/ytmdesktop-youtube-music.rb
==> Name
YouTube Music Desktop App
==> Description
YouTube music client
==> Artifacts
YouTube Music Desktop App.app (App)
==> Analytics
install: 425 (30 days), 1,067 (90 days), 2,865 (365 days)
```

How can I find the log file?

**Comment by Engineer-Extreme** [comment]
I also see this issue almost every time I am using this app. Both on Windows and MacOS.
The app also operates extremely slowly and the UI becomes completely unresponsive and freezes for up to 1-2 minutes on end.

Looking at the process, nothing seems too out of place:
CPU at about 10%
Memory: 450MB for the Renderer and 150MB for the Main process.

I also previously thought that maybe network bottleneck could cause this but after checking there is no such bottleneck I see as the app reaches nowhere close to the available bandwidth on my network.

I don't see such slowdowns with other Electron apps so I am not sure what's causing this.

**Comment by Jus5tRain** [comment]
Found a workaround. I opened the settings while on the loading screen and turned off Discord rich presence. Killed the task and reopened with admin.

**Comment by waldnzwrld** [comment]
This issue still occurs for me, on a fresh install MacOS 26.1 

Had previously installed through homebrew, now nothing works. I have never enabled Discord or any other integrations.

**Comment by tf5bassist** [comment]
I'm running into this same issue.  I finally upgraded from v1.13 to the latest, and every single action, page load, whatever, is SLOOOOOOW.  I'm on macOS 26.2.  Also, does Cmd-, no longer bring up preferences? 

I turned off Discord rich presence, force quit the app, no change.  I can't find the log location on macOS, but let me know where it is and I'll fire that over.

**Comment by MaiastraMan** [comment]
Today I started experiencing exactly the same issue as well :(
I also confirmed that Discord rich presence is off and tried reinstalling, but to no avail.
I hope it can be fixed, because the app is great! :) 

[main.log](https://github.com/user-attachments/files/25246732/main.log)

**Comment by rubylarouge** [comment]
I just did some windows updates and now I am also getting this issue sadly.
I disabled discord rich presence and tried opening in admin mode and that made no difference. 

[main.log](https://github.com/user-attachments/files/25249071/main.log)

**Comment by MuflihMA** [comment]
Hey I just experienced the same issue! 
Here is my log when I turning on the discord presence
```
[2026-02-12 09:48:58.891][main][info] Application launched
[2026-02-12 09:48:58.898][main][info] Application set as default protcol client for 'ytmd'
[2026-02-12 09:48:58.900][main][info] Created memory store
[2026-02-12 09:48:58.906][main][info] Created electron store
[2026-02-12 09:48:58.972][main][info] Application ready
[2026-02-12 09:48:58.973][main][info] Setup IPC handlers
[2026-02-12 09:48:58.974][main][info] Setup permission handlers
[2026-02-12 09:48:58.975][main][info] Unregistered shortcuts
[2026-02-12 09:48:58.975][main][info] Registered shortcuts
[2026-02-12 09:48:58.978][main][info] Created tray icon
[2026-02-12 09:48:59.007][main][info] Created main window
[2026-02-12 09:48:59.015][main][info] Created YTM view
[2026-02-12 09:48:59.016][main][info] Setup taskbar features
[2026-02-12 09:48:59.016][main][info] Integration update: Zoom Factor
[2026-02-12 09:48:59.016][main][info] Starting enabled integrations
[2026-02-12 09:48:59.019][main][info] Integration enabled: Custom CSS
[2026-02-12 09:48:59.019][main][info] Integration enabled: Ratio volume
[2026-02-12 09:48:59.020][main][debug] dipc: initiated connection loop over 10 ids
[2026-02-12 09:48:59.020][main][debug] dipc: connecting to discord at /run/user/1000/discord-ipc-0
[2026-02-12 09:48:59.021][main][info] Integration enabled: Discord presence
[2026-02-12 09:48:59.091][main][debug] dipc: connected to discord at /run/user/1000/discord-ipc-0
[2026-02-12 09:48:59.698][main][warn] (electron) 'console-message' arguments are deprecated and will be removed. Please use Event<WebContentsConsoleMessageEventParams> object instead.
[2026-02-12 09:48:59.698][renderer][info] LegacyDataMixin will be applied to all legacy elements.
Set `_legacyUndefinedCheck: true` on element class to enable.
[2026-02-12 09:49:50.615][main][error] Electron event App#child-process-gone observed {
  type: 'GPU',
  reason: 'abnormal-exit',
  exitCode: 8704,
  serviceName: 'GPU'
}
[2026-02-12 09:50:23.834][main][info] Application quitting
```

I think the discord rich presence and gpu acceleration was the issues and here is the log after I turned off both Discord Presence and GPU acceleration

```
[2026-02-12 09:51:24.004][main][info] Application launched
[2026-02-12 09:51:24.008][main][info] Application set as default protcol client for 'ytmd'
[2026-02-12 09:51:24.010][main][info] Created memory store
[2026-02-12 09:51:24.015][main][info] Created electron store
[2026-02-12 09:51:24.079][main][info] Application ready
[2026-02-12 09:51:24.080][main][info] Setup IPC handlers
[2026-02-12 09:51:24.082][main][info] Setup permission handlers
[2026-02-12 09:51:24.082][main][info] Unregistered shortcuts
[2026-02-12 09:51:24.083][main][info] Registered shortcuts
[2026-02-12 09:51:24.086][main][info] Created tray icon
[2026-02-12 09:51:24.112][main][info] Created main window
[2026-02-12 09:51:24.116][main][info] Created YTM view
[2026-02-12 09:51:24.118][main][info] Setup taskbar features
[2026-02-12 09:51:24.118][main][info] Integration update: Zoom Factor
[2026-02-12 09:51:24.118][main][info] Starting enabled integrations
[2026-02-12 09:51:24.120][main][info] Integration enabled: Custom CSS
[2026-02-12 09:51:24.120][main][info] Integration enabled: Ratio volume
[2026-02-12 09:51:24.681][main][warn] (electron) 'console-message' arguments are deprecated and will be removed. Please use Event<WebContentsConsoleMessageEventParams> object instead.
[2026-02-12 09:51:24.681][renderer][info] LegacyDataMixin will be applied to all legacy elements.
Set `_legacyUndefinedCheck: true` on element class to enable.
```

Is it electron problem? btw I'm running the app on PopOS 22.04 Gnome 42.9 and I'm still using X11, I install it using flatpak, already uninstall and re-install it

**Comment by TheShadowFTW** [comment]
Issue started for me today this evening (10 EST), was working earlier today (12-4 EST). No settings changed between time frames and tried reinstalling both current version and 1 version back. Both discord rich and gpu acceleration are turned off as well.

[main.log](https://github.com/user-attachments/files/25249722/main.log)

**Comment by JosefBvo** [comment]
This issue is getting a lot of traffic! Confirming I am also getting similar behavior. Only started behaving this way today.

[main.log](https://github.com/user-attachments/files/25249760/main.log)

**Comment by artemathician** [comment]
Also getting the same issue today when I didn't yesterday, on my Windows 10 pc, and never enabled discord rich presence. Reinstalled and ran the app again, and issue persists. Including an edited log for just today's log.

[main.log](https://github.com/user-attachments/files/25249779/main.log)

**Comment by MrSkittlesROTR** [comment]
Just came to ask about this as well, app was loading fine 4 hours ago when i turned my pc off, now its doing this loading error.

[2026-02-12 03:45:15.697][main][info] Application launched
[2026-02-12 03:45:15.716][main][info] Created memory store
[2026-02-12 03:45:15.717][main][info] Setup application updater
[2026-02-12 03:45:15.722][main][info] Created electron store
[2026-02-12 03:45:15.767][main][info] Application ready
[2026-02-12 03:45:15.773][main][info] Setup IPC handlers
[2026-02-12 03:45:15.776][main][info] Setup permission handlers
[2026-02-12 03:45:15.777][main][info] Unregistered shortcuts
[2026-02-12 03:45:15.777][main][info] Registered shortcuts
[2026-02-12 03:45:15.798][main][info] Created tray icon
[2026-02-12 03:45:15.858][main][info] Created main window
[2026-02-12 03:45:16.374][main][info] Application launched
[2026-02-12 03:45:16.383][main][info] Created memory store
[2026-02-12 03:45:16.384][main][info] Setup application updater
[2026-02-12 03:45:16.392][main][info] Created electron store
[2026-02-12 03:45:16.424][main][info] Application ready
[2026-02-12 03:45:16.436][main][info] Setup IPC handlers
[2026-02-12 03:45:16.438][main][info] Setup permission handlers
[2026-02-12 03:45:16.439][main][info] Unregistered shortcuts
[2026-02-12 03:45:16.440][main][info] Registered shortcuts
[2026-02-12 03:45:16.456][main][info] Created tray icon
[2026-02-12 03:45:16.531][main][info] Created main window
[2026-02-12 03:45:17.853][main][info] Created YTM view
[2026-02-12 03:45:17.859][main][info] Setup taskbar features
[2026-02-12 03:45:17.860][main][info] Integration update: Zoom Factor
[2026-02-12 03:45:17.860][main][info] Starting enabled integrations
[2026-02-12 03:45:18.329][main][warn] (electron) 'console-message' arguments are deprecated and will be removed. Please use Event<WebContentsConsoleMessageEventParams> object instead.
[2026-02-12 03:45:18.329][renderer][info] LegacyDataMixin will be applied to all legacy elements.
Set `_legacyUndefinedCheck: true` on element class to enable.
[2026-02-12 03:46:42.262][main][info] Application quitting

**Comment by Slapology** [comment]
Reporting the same issue. I've disabled Discord rich presence and retried, still giving me the same error.

[main.log](https://github.com/user-attachments/files/25250319/main.log)

Edit: Uninstalled with Revo Uninstaller, rebooted, fresh install and no longer getting discord rich presence errors but still not loading. 

updated log: [main.log](https://github.com/user-attachments/files/25252059/main.log)

**Comment by johnnykang** [comment]
could it relate to https://github.com/ytmdesktop/ytmdesktop/issues/1601 ?

**Comment by Luiz-Ossinho** [comment]
Same issue, same log as the others, there seems to be other reports for it too: #1659 
couldnt get dev tools to open and also got this log from Squirrel Updater:
```
[12/02/26 03:06:18] info: FileDownloader: Downloading url: https://update.electronjs.org/ytmdesktop/ytmdesktop/win32-x64/2.0.10/RELEASES?id=youtube_music_desktop_app&localVersion=2.0.10&arch=amd64
[12/02/26 03:06:19] info: Program: Finished Squirrel Updater
[12/02/26 03:15:18] info: Program: Starting Squirrel Updater: --checkForUpdate https://update.electronjs.org/ytmdesktop/ytmdesktop/win32-x64/2.0.10
[12/02/26 03:15:18] info: Program: Fetching update information, downloading from https://update.electronjs.org/ytmdesktop/ytmdesktop/win32-x64/2.0.10
[12/02/26 03:15:18] info: CheckForUpdateImpl: Using existing staging user ID: 48052810-fb12-5fc7-a5a7-214291521fa4
[12/02/26 03:15:18] info: CheckForUpdateImpl: Downloading RELEASES file from https://update.electronjs.org/ytmdesktop/ytmdesktop/win32-x64/2.0.10
[12/02/26 03:15:18] info: FileDownloader: Downloading url: https://update.electronjs.org/ytmdesktop/ytmdesktop/win32-x64/2.0.10/RELEASES?id=youtube_music_desktop_app&localVersion=2.0.10&arch=amd64
[12/02/26 03:15:19] info: Program: Finished Squirrel Updater
[12/02/26 03:16:33] info: Program: Starting Squirrel Updater: --checkForUpdate https://update.electronjs.org/ytmdesktop/ytmdesktop/win32-x64/2.0.10
[12/02/26 03:16:33] info: Program: Fetching update information, downloading from https://update.electronjs.org/ytmdesktop/ytmdesktop/win32-x64/2.0.10
[12/02/26 03:16:33] info: CheckForUpdateImpl: Using existing staging user ID: 48052810-fb12-5fc7-a5a7-214291521fa4
[12/02/26 03:16:33] info: CheckForUpdateImpl: Downloading RELEASES file from https://update.electronjs.org/ytmdesktop/ytmdesktop/win32-x64/2.0.10
[12/02/26 03:16:33] info: FileDownloader: Downloading url: https://update.electronjs.org/ytmdesktop/ytmdesktop/win32-x64/2.0.10/RELEASES?id=youtube_music_desktop_app&localVersion=2.0.10&arch=amd64
[12/02/26 03:16:34] info: Program: Finished Squirrel Updater
```

**Comment by m0onb1rd** [comment]
same here app won't start

**Comment by Baddie412** [comment]
Has anyone been able to solve it?

**Comment by Alipoodle** [comment]
With the recent push of V2.0.11 - has this fixed your issue?

**Comment by cacushie** [comment]
Updated to V2.0.11 on Arch, loaded perfectly

**Comment by Baddie412** [comment]
Oh, nice. Version 0.2.11 solved my problem. win11

**Comment by christianbearslyclark** [comment]
Fixed    😎

Tahnks for the Updated .

**Comment by tf5bassist** [comment]
macOS ARM zip appears corrupted.  I've re-downloaded multiple times, returns error when launching app:

<img width="238" height="258" alt="Image" src="https://github.com/user-attachments/assets/628889f9-bcd2-4cac-b203-4dc610bac1e8" />

**Comment by MrSkittlesROTR** [comment]
Thank you on the update, it's working fine now.

**Comment by m0onb1rd** [comment]
> With the recent push of V2.0.11 - has this fixed your issue?

will the fix also be available for the `v2-architecture/rework`? i somehow cannot make it work :(

**Comment by LilithLis** [comment]
On Version 2.0.11  if you still have the same problem just disable discord rich presence should work and least it did work for me.

**Comment by Engineer-Extreme** [comment]
I cleared the cache for the app and the next day the app was back to being snappy and responsive. I don't think that works every time, but it's a worth a try if the app fails to load for you, unable to get past the loading screen.

**Comment by tf5bassist** [comment]
I don't see an option in the app settings to clear the app cache.  

Either way, I've had this issue [going back to even before the mass reporting](https://github.com/ytmdesktop/ytmdesktop/issues/1627#issuecomment-3748331773), but no one's responded to that.

**Comment by Engineer-Extreme** [comment]
Yes, I had been seeing this issue ever since I started using the app quite a while ago.

To clear the cache you can use any OS maintenance utility based on what OS you use.

Anyway the issue seems solved for now.
